import React from 'react';
import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import BackButton from '@/Components/BackButton';
import { BookOpen, Pencil, Plus, Trash2 } from 'lucide-react';

type Unit = { id: number; code: string; name: string; credits: number; faculty: { name: string }; subjects: Array<{ id: number; code: string; name: string; coefficient: string | number }> };
type PageProps = { flash?: { success?: string } };

export default function Subjects({ courseUnits }: { courseUnits: Unit[] }) {
    const { flash } = usePage().props as PageProps;
    const subjectsCount = courseUnits.reduce((count, unit) => count + unit.subjects.length, 0);
    const form = useForm({ course_unit_id: '', code: '', name: '', coefficient: 1 });
    const [editingId, setEditingId] = React.useState<number | null>(null);
    const edit = (subject: Unit['subjects'][number], unitId: number) => { setEditingId(subject.id); form.setData({ course_unit_id: String(unitId), code: subject.code, name: subject.name, coefficient: Number(subject.coefficient) }); };
    const save = (event: React.FormEvent) => { event.preventDefault(); if (!editingId) return; form.put(route('admin.teaching.subjects.update', editingId), { onSuccess: () => { setEditingId(null); form.reset(); } }); };
    return <AuthenticatedLayout header={<div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-indigo-600">Administration · Pédagogie</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-900">Matières enregistrées</h1><p className="mt-1 text-sm text-slate-500">Consultez les ECUE classées par unité d’enseignement.</p></div>}>
        <Head title="Matières enregistrées" />
        <main className="min-h-[calc(100vh-4rem)] bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
            <div className="flex flex-wrap items-center justify-between gap-3"><BackButton href={route('admin.teaching.index')} label="Retour à la gestion des UE"/><Link href={route('admin.teaching.index')} className="inline-flex items-center gap-2 rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-800"><Plus className="h-4 w-4" />Créer une matière</Link></div>
            {flash?.success && <div role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{flash.success}</div>}
            {editingId && <form onSubmit={save} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><h2 className="font-semibold text-slate-800 sm:col-span-2 lg:col-span-4">Modifier la matière</h2><select required value={form.data.course_unit_id} onChange={e => form.setData('course_unit_id', e.target.value)} className="rounded-lg border-slate-300">{courseUnits.map(unit => <option key={unit.id} value={unit.id}>{unit.code} — {unit.name}</option>)}</select><input required maxLength={30} aria-label="Code ECUE" value={form.data.code} onChange={e => form.setData('code', e.target.value)} className="rounded-lg border-slate-300"/><input required maxLength={150} aria-label="Nom de la matière" value={form.data.name} onChange={e => form.setData('name', e.target.value)} className="rounded-lg border-slate-300"/><input required type="number" min="0.01" max="99.99" step="0.01" aria-label="Coefficient" value={form.data.coefficient} onChange={e => form.setData('coefficient', Number(e.target.value))} className="rounded-lg border-slate-300"/><div className="flex gap-2 sm:col-span-2 lg:col-span-4"><button disabled={form.processing} className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white">Enregistrer</button><button type="button" onClick={() => { setEditingId(null); form.reset(); }} className="rounded-lg border border-slate-300 px-4 py-2 text-sm text-slate-700">Annuler</button>{Object.values(form.errors).length > 0 && <span role="alert" className="self-center text-sm text-red-600">{Object.values(form.errors).join(' ')}</span>}</div></form>}
            <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><BookOpen className="h-5 w-5 text-indigo-600"/><p className="text-sm text-slate-600"><strong className="text-slate-900">{subjectsCount}</strong> matière{subjectsCount !== 1 ? 's' : ''} enregistrée{subjectsCount !== 1 ? 's' : ''} dans <strong className="text-slate-900">{courseUnits.length}</strong> UE.</p></div>
            {courseUnits.map(unit => <section key={unit.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-200 bg-slate-50 p-4"><h2 className="font-semibold text-slate-900">{unit.name}</h2><p className="text-xs text-slate-500">{unit.code} · {unit.credits} crédits · {unit.faculty?.name}</p></header>{unit.subjects.length ? <div className="divide-y divide-slate-100">{unit.subjects.map(subject => <div key={subject.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium text-slate-800">{subject.name}</p><p className="text-xs text-slate-500">{subject.code} · coefficient {subject.coefficient}</p></div><div className="flex gap-1"><button type="button" aria-label={`Modifier ${subject.name}`} onClick={() => edit(subject, unit.id)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button><button type="button" aria-label={`Supprimer ${subject.name}`} onClick={() => { if (confirm(`Supprimer la matière ${subject.name} ?`)) router.delete(route('admin.teaching.subjects.destroy', subject.id)); }} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div></div>)}</div> : <p className="p-4 text-sm text-slate-500">Aucune matière dans cette UE.</p>}</section>)}
        </div></main>
    </AuthenticatedLayout>;
}
